# Generated by Django 2.1.2 on 2018-10-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disater_mongo_db_id', models.CharField(blank=True, max_length=100)),
                ('disaster_name', models.CharField(max_length=100)),
                ('disaster_description', models.TextField()),
                ('disaster_image', models.ImageField(blank=True, upload_to='nasa_app/static/nasa_app/img/')),
                ('disaster_background_image', models.ImageField(blank=True, upload_to='nasa_app/static/nasa_app/img/')),
                ('disaster_video_link', models.URLField()),
                ('disater_evac_steps', models.TextField()),
                ('disaster_key_factor', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Disaster',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_weight', models.SmallIntegerField()),
                ('item_description', models.TextField()),
                ('item_quantity_min', models.SmallIntegerField()),
                ('item_quantity_max', models.SmallIntegerField()),
                ('item_expiry_date', models.DateTimeField()),
                ('item_mongo_db_id', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
    ]
