# Generated by Django 2.1.2 on 2018-10-20 15:19

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nasa_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=80, verbose_name='State Name')),
                ('police_number', models.SmallIntegerField(blank=True)),
                ('disaster', multiselectfield.db.fields.MultiSelectField(choices=[('a', 'Hola'), ('b', 'Hello'), ('c', 'Bonjour'), ('d', 'Boas')], max_length=7)),
                ('fire_brigade_number', models.SmallIntegerField(blank=True)),
                ('ambulance_number', models.SmallIntegerField(blank=True)),
                ('my_field', models.CharField(choices=[('a', 'Hola'), ('b', 'Hello'), ('c', 'Bonjour'), ('d', 'Boas')], max_length=1)),
            ],
        ),
    ]
