# Generated by Django 2.1.2 on 2018-10-20 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nasa_app', '0002_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='item_expiry_date',
        ),
        migrations.AddField(
            model_name='items',
            name='item_expiry_time',
            field=models.SmallIntegerField(),
            preserve_default=False,
        ),
    ]
