# Generated by Django 2.1.2 on 2018-10-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasa_app', '0004_remove_items_item_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_expiry_duration',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
