# Generated by Django 2.1.2 on 2018-10-20 22:55

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nasa_app', '0006_auto_20181021_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='disaster_mongo_db_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='disaster_number',
            field=models.SmallIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='disaster',
            field=multiselectfield.db.fields.MultiSelectField(max_length=200),
        ),
    ]
