# Generated by Django 2.1.2 on 2018-10-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasa_app', '0007_auto_20181021_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='ambulance_number',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='disaster_number',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='fire_brigade_number',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='police_number',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
