# Generated by Django 2.1.2 on 2018-10-21 01:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nasa_app', '0008_auto_20181021_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='disaster',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('5', 'Avalanches'), ('4', 'Cyclones'), ('3', 'Tsunami'), ('2', 'Flood'), ('1', 'Earthquake')], max_length=9),
        ),
    ]
